---
title: "Urban Terror - Stats"
author: by Aloe Vera @
output: 
  flexdashboard::flex_dashboard:
    storyboard: true
    source_code: https://github.com/ut-eterstats/ut-eterstats.github.io
    social: menu
    theme: cerulean
---

```{r, include=FALSE}
library(Rcpp)
library(flexdashboard)
library(jsonlite)
library(RSQLite)
library(plotly)
library(dplyr)
library(tidyr)
library(purrr)
library(formattable)
library(forcats)
library(heatmaply)
library(stringr)
library(lubridate)
library(DT)
library(knitr)
```

```{r}
conn_ut4 <- dbConnect(drv = RSQLite::SQLite(), dbname = "./data/data.sqlite")
```

```{r}
df_players <- dbGetQuery(conn_ut4, statement = "SELECT * FROM player")
```

```{r}
df_stats <- dbGetQuery(conn_ut4, statement = "SELECT * FROM xlrstats")
```

```{r}
dbDisconnect(conn_ut4)
```

```{r}
players_dict <- setNames(df_players$name, df_players$guid)
```

```{r}
events_log <- "./data/devel.log"
```

```{r}
# events_log <- "/opt/spunkybot/devel.log.2018-01-19"
```

```{r, include=FALSE}
raw_events <- stream_in(file(events_log))
```

```{r}
options(digits.secs = 3)

df_all_raw_events <- raw_events %>%
  jsonlite::flatten() %>%
  as_data_frame() %>%
  mutate_at("asctime", ~stringr::str_replace(string = .x, ",", ".")) %>%
  mutate_at("asctime", ~as.POSIXct(., format = "%Y-%m-%d %H:%M:%OS"))
```

```{r}
df_all_rounds <- df_all_raw_events %>%
  
  # BUG: No se setea correctamente el nombre del mapa.
  # mutate(
  #   map = str_extract(message, "(?<=Current map: )\\w+")
  # ) %>%
  # fill(map) %>%
  
  mutate(
    round = cumsum(grepl("Init", message))
  ) %>%
  group_by(round) %>%
  mutate(
    round_time = asctime - first(asctime)
  ) %>%
  ungroup()
```

```{r}
df_all_rounds_team <- df_all_rounds %>%
  mutate(
    event_id = row_number()
  ) %>%
  # filter(grepl("Client", message)) %>%
  mutate(
    player_id = str_extract(message, "(?<=Player )\\d+"),
    player_guid = str_extract(message, "(?<=guid )\\w+")
  ) %>%
  group_by(
    player_id
  ) %>%
  fill(player_guid) %>%
  ungroup() %>%
  arrange(
    event_id
  ) %>%
  mutate(
    event_type = if_else(grepl("ClientBegin", message), "player_entered", event_type),
    event_properties.player = coalesce(event_properties.player, player_guid)
  ) %>%
  # select(event_id, asctime, message, event_type, event_properties.player, round, round_time) %>%
  group_by(
    event_properties.player
  ) %>%
  mutate(
    player_session_id = cumsum(grepl("ClientBegin", message)),
    player_team = str_extract(message, "(?<=team )\\w+")
  ) %>%
  fill(player_team) %>%
  ungroup() %>%
  arrange(event_id)
```

```{r}
df_raw_events <- df_all_rounds_team %>%
  
  # Traer sólo las rondas que:
  group_by(round) %>%
  filter(
    # - hayan durado más de 5 minutos.
    max(round_time) > 5 * 60,
    
    # - hayan arrancado antes de las 14hs
    lubridate::hour(min(asctime)) < 14,
    
    # - sean CTF
    any(grepl("flag", event_type))
  ) %>%
  ungroup() %>%
  
  # De esas rondas, traemos las dos últimas
  filter(round >= nth(unique(round), -2)) %>%
  
  # Renombramos las rondas
  mutate(
    round = dense_rank(round)
  )
```

```{r}
stats_mode <- . %>% {
  a <- unique(.)

  match(., a) %>%
    tabulate %>%
    which.max %>%
    a[.]
}
```

```{r}
df_flags_won <- df_raw_events %>%
  filter(event_type == 'flag_captured') %>%
  select(asctime, capturing_team = player_team)

df_sessions <- df_all_rounds_team %>%
  group_by(
    event_properties.player,
    player_session_id
  ) %>%
  summarise(
    player_team = stats_mode(player_team),
    session_start = min(asctime),
    session_end = asctime[if_else(any(grepl("ClientDisconnect", message)), which.max(grepl("ClientDisconnect", message)), NA_integer_)]
  ) %>%
  mutate(
    session_end = coalesce(session_end, lead(session_start))
  ) %>%
  ungroup() %>%
  mutate(
    session_end = coalesce(session_end, max(session_end, na.rm = TRUE))
    ,
    flags_won = list(player_team, session_start, session_end) %>%
      pmap_int(
        ~filter(
          df_flags_won,
          capturing_team == ..1,
          asctime >= ..2,
          asctime < ..3
        ) %>%
          NROW()
      ),
    flags_lost = list(player_team, session_start, session_end) %>%
      pmap_int(
        ~filter(
          df_flags_won,
          capturing_team != ..1,
          asctime >= ..2,
          asctime < ..3
        ) %>%
          NROW()
      )
  )
```

```{r}
df_valid_rounds <- df_raw_events %>%
  group_by(
    round
  ) %>%
  summarise(
    round_start = min(asctime),
    round_end = asctime[if_else(any(grepl("Exit", message)), which.max(grepl("Exit", message)), NA_integer_)]
  ) %>%
  mutate(
    round_end = coalesce(round_end, lead(round_start))
  ) %>%
  ungroup()
```

```{r}
rounds_interval <- lubridate::interval(df_valid_rounds$round_start, df_valid_rounds$round_end)

df_time_played <- df_sessions %>%
  mutate(
    session_interval = lubridate::interval(session_start, session_end),
    round_1_time_played = lubridate::intersect(rounds_interval[1], session_interval) %>% as.period(unit = "seconds") %>% second(),
    round_2_time_played = lubridate::intersect(rounds_interval[2], session_interval) %>% as.period(unit = "seconds") %>% second()
  ) %>%
  filter(player_session_id > 0) %>%
  # mutate(
  #   session_interval = lubridate::interval(session_start, session_end)
  # ) %>%
  group_by(
    event_properties.player
  ) %>%
  summarise_at(
    vars(starts_with("round"), flags_won, flags_lost),
    sum,
    na.rm = TRUE
  ) %>%
  ungroup() %>%
  mutate(
    total_time_played = round_1_time_played + round_2_time_played,
    player = map_chr(event_properties.player, ~players_dict[.x])
  ) %>%
  select(
    player,
    round_1_time_played,
    round_2_time_played,
    total_time_played,
    flags_won,
    flags_lost
  ) %>%
  arrange(-total_time_played)
```

```{r}
df_killers <- df_raw_events %>%
  filter(event_type == 'kill') %>%
  filter(event_properties.killer != 'NONE') %>%
  count(event_properties.killer, event_properties.victim)
```

```{r}
df_knife_kills <- df_raw_events %>%
  filter(
    event_properties.death_cause == 'UT_MOD_KNIFE'
  ) %>%
  mutate(
    killer = map_chr(event_properties.killer, ~players_dict[.x]),
    victim = map_chr(event_properties.victim, ~players_dict[.x])
  ) %>%
  select(
    round,
    round_time,
    killer,
    victim
  ) %>%
  mutate(
    round_time = paste0(as.numeric(round_time) %/% 60, "m", trunc(as.numeric(round_time)) %% 60, "s")
  )
```

```{r}
df_kills <- df_raw_events %>%
  filter(event_type == 'kill') %>%
  filter(event_properties.killer != 'NONE') %>%
  
  # No contar team kills
  filter(!event_properties.team_kill) %>%

  count(event_properties.killer, event_properties.victim) %>%
  
  group_by(event_properties.killer) %>%
  summarise(
    kills = sum(n)
  ) %>%
  ungroup() %>%
  mutate(
    player = map_chr(event_properties.killer, ~players_dict[.x])
  ) %>%
  select(player, kills) %>%
  arrange(-kills)
```

```{r}
df_deaths <- df_killers %>%
  group_by(event_properties.victim) %>%
  summarise(
    deaths = sum(n)
  ) %>%
  ungroup() %>%
  mutate(
    player = map_chr(event_properties.victim, ~players_dict[.x])
  ) %>%
  select(player, deaths) %>%
  arrange(-deaths)
```

### <strong>Flag Stats</strong><br/>Map: ut4_riyadh

```{r}
df_killers %>%
  distinct(event_properties.killer) %>%
  full_join(
    df_raw_events %>%
      filter(grepl("flag", event_type), event_type != 'flag_capture_time') %>%
      count(event_type, event_properties.player) %>%
      ungroup(),
    by = c("event_properties.killer" = "event_properties.player")
  ) %>%
  complete(event_type, event_properties.killer, fill = list(n = 0L)) %>%
  mutate(
    player = map_chr(event_properties.killer, ~players_dict[.x])
  ) %>%
  select(-event_properties.killer) %>%
  spread(
    key = event_type,
    value = n
  ) %>%
  mutate(
    banderas_enemigas_tocadas = flag_dropped + flag_captured
  ) %>%
  rename(
    banderas_capturadas = flag_captured,
    banderas_droppeadas = flag_dropped,
    banderas_recuperadas = flag_returned
  ) %>%
  mutate(
    total_banderas_tocadas = banderas_enemigas_tocadas + banderas_recuperadas
  ) %>%
  arrange(-banderas_capturadas, -total_banderas_tocadas) %>%

  DT::datatable(
    # rownames = FALSE,
    class = 'row-border hover',
    options = list(
      paging = FALSE
      ,
      columnDefs = list(list(className = 'dt-left dt-head-left', targets = "_all"))
    )
  )
```

```{r}
df_raw_events
```

### <strong>Kills Stats</strong>

```{r}
left_color_bar <- function (color = "lightgray", fun = "proportion", ...) 
{
  fun <- match.fun(fun)
  formatter(
    "span",
    style = function(x) style(
      display = "inline-block", 
      `border-radius` = "4px",
      `padding-left` = "4px", #`margin-right` = "20px", `padding-left` = "0px", #
      # padding = "0 0px",
      `background-color` = csscolor(color)
      ,
      width = percent(
        fun(as.numeric(x), ...)
      )
    )
  )
}
```

```{r}
full_join(
  df_kills,
  df_deaths,
  by = "player"
) %>%
  full_join(
    df_time_played %>%
      select(player, total_time_played),
    by = "player"
  ) %>%
  mutate(
    kd_ratio = round(kills / deaths, 2),
    kills_per_minute = round(kills * 60 / total_time_played, 2)
  ) %>%
  mutate(
    total_time_played = paste0(
      sprintf("%02d", as.numeric(total_time_played) %/% 60),
      "m",
      sprintf("%02d", trunc(as.numeric(total_time_played)) %% 60),
      "s"
    )
  ) %>%
  arrange(-kills_per_minute) %>%
  
  select(
    player,
    kills,
    deaths,
    kd_ratio,
    kills_per_minute,
    total_time_played
  ) %>%
  
  formattable(list(
    kills = left_color_bar("lightblue"),
    deaths = left_color_bar("lightblue"),
    kd_ratio = color_tile("transparent", "lightpink"),
    kills_per_minute = color_tile("transparent", "lightpink")
  )) %>%

  formattable::as.datatable(
    # rownames = FALSE,
    class = 'row-border hover',
    options = list(
      paging = FALSE
      ,
      columnDefs = list(list(className = 'dt-left dt-head-left', targets = "_all"))
    )
  ) %>%
  identity()
```

### <strong>Most kills</strong>

```{r}
df_killers %>%
  full_join(
    df_killers,
    by = c("event_properties.victim" = "event_properties.killer", "event_properties.killer" = "event_properties.victim")
  ) %>%
  mutate(
    kills = coalesce(n.x, 0L),
    deaths = coalesce(n.y, 0L),
    balance = kills - deaths
  ) %>%
  mutate(
    killer = map_chr(event_properties.killer, ~players_dict[.x]),
    victim = map_chr(event_properties.victim, ~players_dict[.x])
  ) %>%
  select(
    killer,
    victim,
    kills,
    victim_kills = deaths,
    balance
  ) %>%
  arrange(-balance) %>%
  group_by(killer) %>%
  filter(row_number() == 1) %>%
  ungroup() %>%

  DT::datatable(
    # rownames = FALSE,
    class = 'row-border hover',
    options = list(
      paging = FALSE
      ,
      columnDefs = list(list(className = 'dt-left dt-head-left', targets = "_all"))
    )
  )
```

### <strong>Most deaths</strong>

```{r}
df_killers %>%
  full_join(
    df_killers,
    by = c("event_properties.victim" = "event_properties.killer", "event_properties.killer" = "event_properties.victim")
  ) %>%
  mutate(
    kills = coalesce(n.x, 0L),
    deaths = coalesce(n.y, 0L),
    balance = kills - deaths
  ) %>%
  mutate(
    killer = map_chr(event_properties.killer, ~players_dict[.x]),
    victim = map_chr(event_properties.victim, ~players_dict[.x])
  ) %>%
  select(
    killer,
    victim,
    kills,
    victim_kills = deaths,
    balance
  ) %>%
  arrange(balance) %>%
  group_by(killer) %>%
  filter(row_number() == 1) %>%
  ungroup() %>%
  
  DT::datatable(
    # rownames = FALSE,
    class = 'row-border hover',
    options = list(
      paging = FALSE
      ,
      columnDefs = list(list(className = 'dt-left dt-head-left', targets = "_all"))
    )
  )
```

### <strong>Kills heatmap</strong>

```{r}
df_killers %>%
  full_join(
    df_killers,
    by = c(
      "event_properties.victim" = "event_properties.killer",
      "event_properties.killer" = "event_properties.victim"
    )
  ) %>%
  mutate(
    # kills = coalesce(n.x, 0L),
    # deaths = coalesce(n.y, 0L),
    kills = n.x,
    deaths = n.y,
    balance = kills - deaths
  ) %>%
  mutate(
    killer = map_chr(event_properties.killer, ~players_dict[.x]),
    victim = map_chr(event_properties.victim, ~players_dict[.x])
  ) %>%
  select(
    killer,
    victim,
    kills
  ) %>%
  spread(victim, kills) %>%
  {
    my_row_names <- pull(., killer)
    m <- as.matrix(select(., -killer))

    rownames(m) <- my_row_names

    m[is.na(m)] <- 0

    heatmaply(
      m,
      xlab = 'victims', ylab = 'killers',
      k_col = 2, k_row = 2,
      colors = viridis::inferno,
      seriate = "GW"
      # plot_method = "plotly",
      # row_dend_left = TRUE,
      # margins = c(120, 0, 0, NA)
    )
  }
```

### <strong>Knife Kills</strong>

```{r}
df_knife_kills %>%
  DT::datatable(
    rownames = FALSE,
    class = 'row-border hover',
    options = list(
      paging = FALSE
      ,
      columnDefs = list(list(className = 'dt-left dt-head-left', targets = "_all"))
    )
  ) %>%
  
  identity()
```

### <strong>Stats Globales (TEMP)</strong><br>Por el momento, incluye el warmup. En un futuro, sólo va a contar "el bueno". 

```{r}
df_stats %>%
  arrange(-ratio) %>%
  mutate(
    rank = row_number(),
    hs_kill = round(headshots / kills, 2)
  ) %>%
  select(rank, name, kills, deaths, headshots, ratio, max_kill_streak, hs_kill)  %>%
  
  DT::datatable(
    rownames = FALSE,
    class = 'row-border hover',
    options = list(
      paging = FALSE
      ,
      columnDefs = list(list(className = 'dt-left dt-head-left', targets = "_all"))
    )
  )
```

### <strong>Stats Globales</strong><br>DESACTUALIZADO 

```{r}
readRDS("dfg.Rds") %>%
  
  
  formattable(list(
    kills = left_color_bar("lightblue"),
    deaths = left_color_bar("lightblue"),
    kd_ratio = color_tile("transparent", "lightpink"),
    kills_per_minute = color_tile("transparent", "lightpink")
  )) %>%

  formattable::as.datatable(
    # rownames = FALSE,
    class = 'row-border hover',
    options = list(
      paging = FALSE
      ,
      columnDefs = list(list(className = 'dt-left dt-head-left', targets = "_all"))
      , scrollX = TRUE
    )
  )
```



